### ISSUE TITLE
select for QueryObserverOptions is not typed

### ISSUE THREAD

**Issue by QzCurious** [ecyrbe/zodios#158] opened 2022-09-28 02:17 UTC
According to [react-query](https://react-query-v3.tanstack.com/reference/useQuery). `select` function in `QueryObserverOptions` will get returned data from query function.

![image](https://user-images.githubusercontent.com/38932402/192671513-dfda5dc0-cead-4ef0-a06f-15f75b34d77c.png)

This is where zodios failed to infer the type of return data.

![image](https://user-images.githubusercontent.com/38932402/192671375-1a99e9e8-59a5-4014-ab13-59f21b483768.png)

**Comment by ecyrbe** [comment] 2022-09-28 10:33
Thank you,
I found the Root cause of this issue.
Fix incoming

**Comment by ecyrbe** [comment] 2022-09-28 11:02
This is now fixed in `@zodios/react` version 9.4.2 and `@zodios/solid` version 9.1.2

**Closed** 2022-09-28 11:02 UTC
